# Generated by Django 2.2.4 on 2019-11-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191125_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='pro_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='pro_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom',
            field=models.CharField(max_length=200),
        ),
    ]
